#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt update

sudo apt install nginx

sudo nano /usr/share/nginx/html/404.html

<!DOCTYPE html>

<html>

<head>

	<title>404 Not Found</title></head>

<body>

	<h1>404 Not Found</h1>

	<p>Ceci n\'est pas une page.</p>
</body>

</html>


sudo nano /etc/nginx/sites-available/default


sudo nginx -t

error_page 404 /404.html;

location = /404.html {

    internal;

}

sudo nginx -t

sudo /etc/init.d/nginx reload



"""
#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y nginx 
echo "Hello World!" > index.html
sudo mv index.html /var/www/html


echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
"""
